version: "3.8"
services:
  mysqldb:
    container_name: mysql1db
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./pokemon-app
    env_file: ./.env
    ports:
      - 8081:8081
    expose:
      - 8081
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: